<a href="https://colab.research.google.com/github/ruslanmv/Data-Science-in-Jupyter-Notebook/blob/master/Data_Science_Colab_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reference of Data Science in Jupyter Notebook
by ruslanmv  

Hello everyone,  I have created this notebook to summarize some concepts of Data Science that may help you in your projects of your Company.
I wanted to collect some of the essential tools used everyday as Data Scientist.

IMPORTANT NOTE: This notebook is designed to run as a Colab. Running it on your local machine might result in some of the code blocks throwing errors.

Run the code below to download the compressed datasets data.zip.


In [249]:
!wget https: // github.com/ruslanmv/Data-Science-in-Jupyter-Notebook/raw/master/data.zip


--2022-06-25 13:22:11--  https://github.com/ruslanmv/Data-Science-in-Jupyter-Notebook/raw/master/data.zip
Resolving github.com (github.com)... 52.69.186.44
Connecting to github.com (github.com)|52.69.186.44|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/ruslanmv/Data-Science-in-Jupyter-Notebook/master/data.zip [following]
--2022-06-25 13:22:11--  https://raw.githubusercontent.com/ruslanmv/Data-Science-in-Jupyter-Notebook/master/data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28337418 (27M) [application/zip]
Saving to: ‘data.zip’

data.zip            100%[===================>]  27.02M   146MB/s    in 0.2s    

2022-06-25 13:22:12 (146 MB/s) - ‘data.zip’ saved [28337418/28337418]



You can then unzip the archive using the zipfile module.

In [250]:
import zipfile
# Unzip the dataset
local_zip = './data.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('./')
zip_ref.close()


### Table of Contents

-   [Section 1: Python for Data Science](#section-1)
-   [Section 2: Importing Data](#section-2)
-   [Section 3: Data Wrangling with Pandas](#section-3)
-   [Section 4: Data Analysis with Numpy](#section-4)
-   [Section 5: Data Visualization with Matplotlib](#section-5)
-   [Section 7: Machine Learning with Scikit-Learn](#section-7)
-   [Section 8: SciPy](#section-8)
-   [Section 9: Neural Networks with Keras](#section-9)
-   [Section 10: PySpark & Spark SQL](#section-10)

# Python for Data Science

The first thing that you should know is the precedence of the operators in Python. You can remember the PEMDAS rule:


|  | Operation      |
|--|----------------|
|P | Parentheses.   |
|E | Exponentiation.|
|M | Multiplication.| 
|D | Division.      |
|A | Addition.      |
|S | Subtraction.   |

## Types and Type Conversion

In [68]:
str(3.45)  # Variables to strings


'3.45'

In [69]:
int(3.45)  # Variables to integers


3

In [70]:
float(5)  # Variables to floats


5.0

In [71]:
bool(True)  # Variables to boolean


True

### Libraries

Data analysis -\> **pandas**

Scientific computing -\> **numpy**

2D plotting -\> **matplotlib**

Machine learning -\> **Scikit-Learn**

### Import Libraries

In [72]:
import numpy
import numpy as np


### Selective import

In [73]:
from math import pi


### Strings

In [74]:
my_string = 'thisStringisAwesome'


In [75]:
my_string


'thisStringisAwesome'

**String Operation**

In [76]:
my_string * 2


'thisStringisAwesomethisStringisAwesome'

In [77]:
my_string + 'Innit'


'thisStringisAwesomeInnit'

In [78]:
'm' in my_string


True

**String** **Indexing**
Index starts at 0

In [79]:
my_string[3]


's'

In [80]:
my_string[4:9]


'Strin'

In [81]:
my_string.lower()  # String to lowercase


'thisstringisawesome'

In [82]:
my_string.count('w')  # Count String elements


1

In [83]:
my_string.replace('e', 'i')  # Replace String elements


'thisStringisAwisomi'

In [84]:
my_string.strip()  # Strip whitespoces


'thisStringisAwesome'

### Lists

In [85]:
my_list = [1, 2, 3, 4]


In [86]:
my_array = np.array(my_list)


In [87]:
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])


**Selecting Numpy Array Elements**
Index starts at 0
Subset

In [88]:
my_array[1]  # Select item at index 1


2

Slice

In [89]:
my_array[0:2]  # Select items at index 0 and 1


array([1, 2])

**Subset 2D Numpy arrays**

In [90]:
my_2darray[:, 0]  # my_2darroy[rows, columns]


array([1, 4])

**Numpy Array Operations**

In [91]:
my_array > 3


array([False, False, False,  True])

In [92]:
my_array * 2


array([2, 4, 6, 8])

In [93]:
my_array + np.array([5, 6, 7, 8])


array([ 6,  8, 10, 12])

**Numpy Array Functions**

In [94]:
my_array.shape  # Get the dimensions of the array


(4,)

In [95]:
other_array = np.array([9])


In [96]:
np.append(my_array, other_array)  # Append items to on array


array([1, 2, 3, 4, 9])

In [97]:
np.insert(my_array, 1, 5)  # Insert items in on array


array([1, 5, 2, 3, 4])

In [98]:
np.delete(my_array, [1])  # Delete items in on array


array([1, 3, 4])

In [99]:
np.mean(my_array)  # Mean of the array


2.5

In [100]:
np.median(my_array)  # Median of the array


2.5

In [101]:
np.corrcoef(my_array)  # Correlation coefficient


1.0

In [102]:
np.std(my_array)  # Standard deviation


1.118033988749895

### Lists

In [103]:
a = 'is'


In [104]:
b = 'nice'


In [105]:
my_list = ['my', 'list', a, b]


In [106]:
my_list2 = [[4, 5, 6, 7], [3, 4, 5, 6]]


**Selecting List Elements**

Index starts at 0


Subset

In [107]:
my_list[1]  # Select item at index 1


'list'

In [108]:
my_list[-3]  # Select 3rd last item


'list'

**Slice**

In [109]:
my_list[1:3]  # Select items at index 1 and 2


['list', 'is']

In [110]:
my_list[1:]  # Select items after index 0


['list', 'is', 'nice']

In [111]:
my_list[:3]  # Select items before index 3


['my', 'list', 'is']

In [112]:
my_list[:]  # Copy my_list


['my', 'list', 'is', 'nice']

**Subset Lists of Lists**

In [113]:
my_list2[1][0]  # my_list[list][itemOfList]


3

In [114]:
my_list2[1][:2]


[3, 4]

**List Operations**

In [115]:
my_list + my_list


['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [116]:
2*my_list


['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

**List Methods**

In [50]:
my_list.index(a)  # Get the index of an item


2

In [51]:
my_list.count(a)  # Count on item


1

In [52]:
my_list.append('!')  # Append on item ot a time


In [53]:
my_list.remove('!')  # Remove  on  item


In [54]:
del(my_list[0:1])  # Remove an item


In [55]:
my_list


['list', 'is', 'nice']

In [56]:
my_list.reverse()  # Reverse the list


In [57]:
my_list.extend('!')  # Append on item


In [58]:
my_list.pop(-1)  # Remove on item


'!'

In [59]:
my_list.insert(0, '!')  # Insert on item


In [117]:
my_list.sort()  # Sort the list


**Asking For Help**


help(str)

# Section 2

### **Importing Data**

**Most of the time, you’ll use either NumPy or pandas to import your
data:**

In [118]:
import numpy as np
import pandas as pd


**Help**

     np.info(np.ndarray.dtype)
     help(pd.read_csv)


In [119]:
df = pd.read_csv('data/titanic.csv')


In [120]:
df.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### Text Files

**Plain Text Files**

In [121]:
filename = 'data/huck_finn.txt'
file = open(filename, mode='r')  # Open the file for reading
text = file.read()  # Reado file's contents
print(file.closed)  # Check whether file is closed
file.close()  # Close file
# print(text)


False


In [122]:
with open('data/huck_finn.txt', 'r') as file:
    print(file.readline())  # Read single line
    print(file.readline())
    print(file.readline())






The Project Gutenberg EBook of Adventures of Huckleberry Finn, Complete



## Table Data: Flat Files

**Importing Flat Files with NumPy**

In [123]:
filename = 'data/huck_finn.txt'
file = open(filename, mode='r')  # Open the file for reading
text = file.read()  # Reado file's contents
print(file.closed)  # Check whether file is closed
file.close()  # Close file
# print(text)


False


**Files with one data type**


In [124]:
filename = 'data/mnist.txt'
data = np.loadtxt(filename,
                  delimiter=',',  # String used to separate values
                  skiprows=2,  # Skip the first 2 lines
                  usecols=[0, 2],  # Read the 1st and 3rd column
                  dtype=str)  # The type of the resulting array



**Files with mixed data type**


In [189]:
filename = 'data/breast-cancer.csv'
data = np.genfromtxt(filename,
                     delimiter=',',
                     names=True,  # Look for column header
                     dtype=None)
data_array = np.recfromcsv(filename)
# The default dtype of the np.recfromcsv() function is None



### Importing Flat Files with Pandas



In [185]:
filename = 'data/winequality-red.csv'
data = pd.read_csv(filename,
                   nrows=5,  # Number of rows of file to read
                   header=None,  # Row number to use as col names
                   sep='\t',  # Delimiter to use
                   comment='#',  # Character to split comments
                   na_values=[""])  # String to recognize as NA/NaN



## Exploring Your Data

**NumPy Arrays**



In [182]:
data_array.dtype  # Data type of array elements


dtype((numpy.record, [('id', '<i8'), ('clump_thickness', '<i8'), ('uniformity_of_cell_size', '<i8'), ('uniformity_of_cell_shape', '<i8'), ('marginal_adhesion', '<i8'), ('single_epithelial_cell_size', '<i8'), ('bare_nuclei', '<i8'), ('bland_chromatin', '<i8'), ('normal_nucleoli', '<i8'), ('mitoses', '<i8'), ('class', '<i8')]))

In [183]:
data_array.shape  # Array dimensions


(683,)

In [184]:
len(data_array)  # Length of array


683


**Pandas DataFrames**



In [190]:
df = pd.read_csv('data/titanic.csv')


In [191]:
df.head()  # Return first DataFrame rows


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [192]:
df.tail()  # Return last OataFrame rows


PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [193]:
df.index  # Describe index


RangeIndex(start=0, stop=891, step=1)

In [194]:
df.columns  # Describe OataFrame columns


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [195]:
df.info()  # Info an DataFrame


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [196]:
data_array = df.values  # Convert a DataFrame to an a NumPy array



**SAS File**



In [251]:
try:
    print("Importing sas7bda module")
    from sas7bdat import SAS7BDAT
except ModuleNotFoundError:
    print("Installing sas7bda module")
    !pip install sas7bdat


Importing sas7bda module


In [252]:
from sas7bdat import SAS7BDAT
with SAS7BDAT('data/cars.sas7bdat') as file:
    df_sas = file.to_data_frame()



**Stata File**


In [253]:
data = pd.read_stata('data/TBL5-1.DTA')



**Excel Spreadsheets**


In [254]:
try:
    print("Importing xlrd and openpyxl  modules")
    import xlrd
    import openpyxl
except ModuleNotFoundError:
    print("Installing xlrd, openpyxl  modules")
    !pip install xlrd
    !pip install openpyxl


Importing xlrd and openpyxl  modules


In [255]:
file = 'data/urbanpop.xlsx'
data = pd.ExcelFile(file)


In [256]:
df_sheet2 = data.parse('1960-1966', skiprows=[1])


In [257]:
df_sheet2.head()


country       1960          1961          1962          1963  \
0         Albania   494443.0  5.118028e+05  5.294389e+05  5.473767e+05   
1         Algeria  3293999.0  3.515148e+06  3.739963e+06  3.973289e+06   
2  American Samoa        NaN  1.366030e+04  1.416580e+04  1.475893e+04   
3         Andorra        NaN  8.723921e+03  9.700346e+03  1.074838e+04   
4          Angola   521205.0  5.482650e+05  5.796954e+05  6.120867e+05   

           1964          1965          1966  
0  5.655718e+05  5.839829e+05  6.025122e+05  
1  4.220987e+06  4.488176e+06  4.649105e+06  
2  1.539642e+04  1.604482e+04  1.669311e+04  
3  1.186586e+04  1.305275e+04  1.421681e+04  
4  6.452616e+05  6.791091e+05  7.178334e+05

In [258]:
df_sheetl = data.parse(1, parse_cols=[0], skiprows=[1])


In [259]:
df_sheetl.head()


country          1967          1968          1969          1970  \
0         Albania  6.211798e+05  6.399645e+05  6.588531e+05  6.778391e+05   
1         Algeria  4.826104e+06  5.017299e+06  5.219332e+06  5.429743e+06   
2  American Samoa  1.734866e+04  1.799551e+04  1.861868e+04  1.920639e+04   
3         Andorra  1.543962e+04  1.672699e+04  1.808832e+04  1.952896e+04   
4          Angola  7.574963e+05  7.984593e+05  8.412620e+05  8.864016e+05   

           1971          1972          1973          1974  
0  6.989322e+05  7.202066e+05  7.416810e+05  7.633855e+05  
1  5.619042e+06  5.815734e+06  6.020647e+06  6.235114e+06  
2  1.975202e+04  2.026267e+04  2.074197e+04  2.119438e+04  
3  2.092873e+04  2.240584e+04  2.393705e+04  2.548198e+04  
4  9.550101e+05  1.027397e+06  1.103830e+06  1.184486e+06


To access the sheet names, use the sheet_names attribute:



In [260]:
data.sheet_names


['1960-1966', '1967-1974', '1975-2011']

In [261]:
import pandas as pd



### Relational Databases



![title](https://github.com/ruslanmv/Data-Science-in-Jupyter-Notebook/blob/master/data/Northwind_ERD.png?raw=1)

In [262]:
import sqlalchemy as db


In [267]:
# Connect with the database
engine = db.create_engine('sqlite:///data/Northwind_large.sqlite')


In [268]:
connection = engine.connect()


In [269]:
# Retrieve the Metadata
metadata = db.MetaData()


In [270]:
# Load the shows table
shows = db.Table('Region', metadata, autoload=True, autoload_with=engine)


With our table loaded, let’s prepare a query to select all the records from the shows table. In regular SQL, to select all the records, it is “SELECT * FROM shows”. The SQLAlchemy Core query looks like this.

In [271]:
# Prepare the Query
query = db.select([shows])


In [272]:
# Execute the Query
result_proxy = connection.execute(query)


In [273]:
# Fetch the data.
result_set = result_proxy.fetchall()


In [274]:
print(result_set)


[(1, 'Eastern'), (2, 'Western'), (3, 'Northern'), (4, 'Southern')]



**Querying Relational Databases**




Use the table_names() method to fetch a list of table names:


In [275]:
table_names = engine.table_names()


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  """Entry point for launching an IPython kernel.


In [276]:
table_names


['Category',
 'Customer',
 'CustomerCustomerDemo',
 'CustomerDemographic',
 'Employee',
 'EmployeeTerritory',
 'Order',
 'OrderDetail',
 'Product',
 'Region',
 'Shipper',
 'Supplier',
 'Territory']

In [277]:
con = engine.connect()


In [278]:
rs = con.execute('SELECT * FROM Customer')


In [279]:
df = pd.DataFrame(rs.fetchall())


In [280]:
df.head()


0                                   1                   2   \
0  ALFKI                 Alfreds Futterkiste        Maria Anders   
1  ANATR  Ana Trujillo Emparedados y helados        Ana Trujillo   
2  ANTON             Antonio Moreno Taquería      Antonio Moreno   
3  AROUT                     Around the Horn        Thomas Hardy   
4  BERGS                  Berglunds snabbköp  Christina Berglund   

                     3                              4            5   \
0  Sales Representative                  Obere Str. 57       Berlin   
1                 Owner  Avda. de la Constitución 2222  México D.F.   
2                 Owner                Mataderos  2312  México D.F.   
3  Sales Representative                120 Hanover Sq.       London   
4   Order Administrator                Berguvsvägen  8        Luleå   

                6         7        8               9               10  
0   Western Europe     12209  Germany     030-0074321     030-0076545  
1  Central America     05021   Mexico    (5) 555-4729    (5) 555-3745  
2  Central America     05023   Mexico    (5) 555-3932            None  
3    British Isles   WA1 1DP       UK  (171) 555-7788  (171) 555-6750  
4  Northern Europe  S-958 22   Sweden   0921-12 34 65   0921-12 34 67

In [281]:
df.columns = rs.keys()


In [282]:
con.close()



Using the context manager with


In [291]:
with engine.connect() as con:
    rs = con.execute('SELECT CompanyName FROM Customer')
    df = pd.DataFrame(rs.fetchmany(size=5))
    df.columns = rs.keys()
df.head()


CompanyName
0                 Alfreds Futterkiste
1  Ana Trujillo Emparedados y helados
2             Antonio Moreno Taquería
3                     Around the Horn
4                  Berglunds snabbköp


**Querying relational databases with pandas**


In [292]:
df = pd.read_sql_query("SELECT *  FROM Customer", engine)



Pickled File



In [285]:
import pickle
with open('data/pickled_fruit.pkl', 'rb') as file:
    pickled_data = pickle.load(file)


## Exploring Dictionaries

**Querying relational databases with pandas**



In [293]:
print(df.keys())  # Print dictionary keys


Index(['Id', 'CompanyName', 'ContactName', 'ContactTitle', 'Address', 'City',
       'Region', 'PostalCode', 'Country', 'Phone', 'Fax'],
      dtype='object')


In [295]:
for key in df.keys():  # Print dictionary keys
    print(key)


Id
CompanyName
ContactName
ContactTitle
Address
City
Region
PostalCode
Country
Phone
Fax



### Navigating Your FileSystem

**Magic Commands**




!ls #List directory contents of files and directories
%cd .. #Change current working directory
%pwd #Return the current working directory path




**OS Library**



In [300]:
import os
os.mkdir("newdir")  # Create a new directory


In [302]:
path = "data"
wd = os.getcwd()  # Store the name of current directory in a string
os.listdir(wd)  # Output contents of the directory in a list
os.chdir(path)  # Change current working directory
os.rename("testl.txt",  # Rename a file
          "test2.txt")
os.remove("test1. txt")  # Oelete an existing file


FileNotFoundError: ignored


**Pivot**



In [ ]:

df3 = df2.pivot(inde x='Date',  # Spread rows into columns
                col umns='Type',
                values='Value')



**Pivot Table**


In [ ]:


df4 = pd.pivot_table(df2,  # Spread rows into
columns values='Value', index='Date', columns='Type'])



**Stack** / **Unstack**



In [ ]:

stacked = df5.stack()  # Pivot o level of column labels
stacked.unstack()  # Pivot o level of index labels



**Melt**



In [ ]:
pd.melt(df2,  # Gather columns into rows
        id _vars=['Date'],
        value_var s=['Type', 'Value'],
        value name='Observations')


### Iteration

In [ ]:
df.iteritems()  # {Column-index, Series) pairs
df.iterrows()  # {Row-index, Series) pairs


### Missing Data

In [ ]:
df.dropna()  # Drop NaN values
df3.fillna(df3.mean())  # Fill NaN values with o predetermined value
df2.replace("a", "f")  # Replace values with others



### Advanced Indexing

**Selecting**



In [ ]:
df3.loc[:, (df3 > 1).any()]  # Select cols with any vols >1
df3.loc[:, (df3 > 1).all()]  # Select cols with vols> 1
df3.loc[:, df3.isnull().any()]  # Select cols with NaN
df3.loc[:, df3.notnull().all()]  # Select cols without NaN



**Indexing With** isin ()


In [ ]:
df[(df.Country.isin(df2.Type))]  # Find some elements
df.filter(iterns="a", "b"])  # Filter on values
df.select(lambda x: not x % 5)  # Select specific elements




**Where**



In [ ]:

s.where(s > 0)  # Subset the data



**Query**



In [ ]:
df6.query('second > first')  # Query DataFrame


In [ ]:
**Setting/Resetting Index**


In [ ]:
df.set_index('Country')  # Set the index
df4 = df.reset_index()  # Reset the index
df = df.rename(index=str,  # Rename
               DataFrame columns={"Country": "cntry",
                                  "Capital':"cptl",
                                  "Population": pplt})


**Reindexing**

In [ ]:
s2 = s.reindex(['a', 'c', 'd', 'e', 'b'])


**Forward Filling**

In [ ]:
df.reindex(range(4),
           method='ffill')


        Country Capital     Population  
    0   Belgium Brussels    11190846    
    1   India   New Delhi   1303171035  
    2   Brazil  Brasilia    207847528   
    3   Brazil  Brasilia    207847528

**Backward Filling**

In [ ]:
s3 = s.reindex(range(5),
               method='bfill')


In [ ]:
0   3
1   3
2   3
3   3
4   3


**Multilndexing**

In [ ]:
arrays = [np.array([l, 2, 3]),
          np.array([5, 4, 3])]
df5 = pd.DataFrame(np.random.rand(3, 2), index=arrays)
tuples = list(zip(*arrays))
index = pd.Multilndex.from_tuples(tuples,
                                  names=['first', 'second'])
df6 = pd.DataFrame(np.random.rand(3, 2), index=index)
df2.set_index(["Date", "Type"])


### Duplicate Data

In [ ]:
s3.unique()  # Return unique values
df2.duplicated('Type')  # Check duplicates
df2.drop_dup licates('Type', keep='last')  # Drop duplicates
df.index.duplicated()  # Check index duplicates


### Grouping Data

**Aggregation**

In [ ]:
df2.groupby(by=['Date', 'Type']).mean()
df4.groupby(level=0).sum()
df4.groupby(level=0).agg({'a': lambda x: sum(x)/len(x), 'b': np.sum})


**Transformation**

In [ ]:
def customSum(x): return (x+x % 2)


df4.groupby(level=0).transform(customSum)


## Combining Data

**Merge**

In [ ]:
pd.merge(data1,
         data2,
         how='left',
         on='X1')


In [ ]:
pd.merge(data1,
         data2,
         how='right',
         on='X1')


In [ ]:
pd.merge(data1,
         data2,
         how='inner',
         on='X1')


In [ ]:
pd.merge(data1,
         data2,
         how='outer',
         on='X1')


**Join**

In [ ]:
datal.join(data2, ho w='righ t')


**Concatenate**

**Vertical**

In [ ]:
s.append(s2)


**Horizontal/Vertical**

In [ ]:
pd.concat([s, s2], axis=l, keys=['One', 'Two'])
pd.concat([data1, data2], axis=l, join='inner')


### Dates

In [ ]:
df2['Date'] = pd.to_da tetime(d f2['Date'])
df2['Date'] = pd.da te_range('2000-1-1',
                             periods=6, freq='M')
dates = [datetime(2012, 5, 1), datetime(2012, 5, 2)]
index = pd.Datetimelndex(dates)
index = pd.date_range(datetime(2012, 2, 1), end, freq='BM')


### Visualization

In [ ]:
import matplotlib.pyplot as plt
s.plot()
plt.show()


In [ ]:
df2.plot()
plt.show()


# Section 3

# Data Wrangling with Pandas

The **Pandas** library is built on NumPy and provides easy-to-use **data
structures** and **data analysis** tools for the Python programming
language.

**Use the following import convention:**

In [1]:
import pandas as pd


### Pandas Data Structure

**Series**

A **one-dimensional** labeled array

capable of holding any data type

In [4]:
s = pd.Series([3, -5, 7, 5], index=['a', 'b', 'c', 'd'])


**Dataframe**

A **two-dimensional** labeled data structure with columns of potentially
different types

In [ ]:
data = {'Country': ['Belgium', 'India ', ' Brazil'],
        'Capital': ['Brussels', 'New Delhi', 'Brasilia'],
        'Population': [111908s6, 1303171035, 207847528]}
df = pd.DataFrame(data, columns=['Country', 'Capital', 'Population'])


**Dropping**

In [ ]:
s.drop(['a', 'c'])  # Drop values from rows (axis=B)
df.drop('Country', axis=l)  # Drop values from columns(axis=l)


**Sort & Rank**

In [ ]:
df.sort_index()  # Sort by labels along an axis
df.sort_values(by='Country')  # Sort by the values along on axis
df.rank()  # Assign ranks to entries


### I/O

**Read and Write to CSV**

In [ ]:
pd.read_csv('file.csv', header=None, nrows=5)
df.to_csv('myDataFrame.csv')


**Read and Write to Excel**

In [ ]:
pd.read_excel('file.xlsx')
df.to_excel('dir/myDataFrame.x lsx', sheet_name='Sheet1')


In [ ]:
Read multiple sheets from the same file


In [ ]:
xlsx = pd.ExcelFile('file.xls')
df = pd.read_excel(xlsx, 'Sheet1')


In [ ]:
**Read and Write to SQL Query or Database Table**


In [ ]:
from sqlalchemy import create_engine
engine = create_eng ine('sqlite:///:memory:')
pd.read_sql("SELECT* FROM my_table;", engine)
pd.read_sql_ tabl e('my_ table', engine)
pd.read_sql_query("SELECT * FROM my_table;", engine)


In [ ]:
read_sql() is a convenience wrapper around read_sql_table() and
read_sql_query()


In [ ]:
df.to_sql('myDf', engine)


In [ ]:
# Selection

**Getting**


In [ ]:
s['b']  # Get one element


In [ ]:
df[1:]  # Get subset of a DataFrome


In [ ]:
Country Capital Population 1 India New Delhi 1303171035
2 Brazil Brasilia 207847528


In [ ]:
**Selecting, Boolean Indexing ** & **Setting**

**By Position**


In [ ]:
df.iloc[[0], [0]]  # Select single value by row & column
'Belgium'
df.iat([0], [0])
'Belgium'


In [ ]:
**By Label**


In [ ]:
# Select single value by row & column labels 'Belgium'
df.loc[[0], ['Country']]
df.at([0], ['Country ']) 'Belgium'


In [ ]:
**By Label/Position**


In [ ]:
df.ix[2]  # Select single row of subset of rows
Country Brazil Capital Brasilia Population 207847528
df.ix[:, 'Capital']  # Select a single column of subset of columns


In [ ]:
df.ix[1, 'Capital']  # Select rows and columns 'New Delhi'


**Boolean Indexing**

In [ ]:
s[N(s > 1)]  # Series s where value is not >l
s[(s < -1) I(s > 2)]  # s where value is f-1 or >2
df[df['Population'] > 1200000000]  # Use filter to adjust DataFrame


**Setting**

In [ ]:
s['a'] = 6  # Set index a of Series s to 6


### Retrieving Series/DataFrame Information

**Basic Information**

In [ ]:

df.shape  # (rows,columns)
df.index  # Describe index
df.columns  # Describe DataFrame columns
df.info()  # Info on DataFrame
df.count()  # Number of non-NA values


In [ ]:

**Summary**

df.sum()  # Sum of values
df.cumsum()  # Cummulative sum of values
df.min() / df.max()  # 11inimum/maximum values
df.idxmin()/df.idxmax()  # Minimum/Maximum index value
df.describe()  # Summary statistics
df.mean()  # 11ean of values
df.median()  # Median of values



### Applying Functions

In [ ]:

def f(x): return X*2


df.apply(f)  # Apply function
df.applymap(f)  # Apply function element-wise



**Data Alignment**

**Internal Data Alignment**

In [ ]:

 s3 = pd.Series([7, -2, 31, index=['a', 'c', 'd'])
 s + s3
a 10.0
b NaN
C 5.0
d 7.0



**Arithmetic Operations with Fill Methods**

**You can also do the internal data alignment yourself with the help of
the fill methods:**

In [ ]:

s.add(s3, fill_values=0) a 10.0
b - 5. 0
C 5.0
d 7.0
s.sub(s3, fill_value=2)
s.div(s3, fill_value=4)
s.mul(s3, fill_value=3)



# Section 4

## Data Analysis with Numpy

The NumPy library is the core library for scientific computing in
Python. It provides a high performance multidimensional array object ,
and tools for working with these arrays

**Use the following import convention**

In [ ]:
import numpy as np



**Creating Array**

In [ ]:

a = np.array([l, 2, 3])
b = np.array([(l.5, 2, 3), (4, 5, 6)], dtype=float)
c = np.array([[(l.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)



**Initial Placeholders**

In [ ]:

np.zeros((3, 4))  # Create an array af zeros
np.ones((2, 3, 4), dtype=np.int16)  # Create an array of ones
# Create an array of evenly spaced values (step value)
d = np.arange(10, 25, 5)
# Create an array of evenly spaced values (number of samples)
np.linspace(0, 2, 9)
e = np.full((2, 2), 7)  # Create a constant array
f = np.eye(2)  # Create a 2X2 identity matrix
np.random.random((2, 2))  # Create an array with random values
np.empty((3, 2))  # Create an empty array



### **I/O**

**Saving** **&** **Loading On Disk**

In [ ]:

np.save('my_array', a)
np.save('array.npz', a, b)
np.load('my_array.npy ')



**Saving & Loading Text Files**

In [ ]:

np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")



### Inspecting Your Array

In [ ]:

a.shape  # Array dimensions
len(a)  # Length of array
b.ndim  # Number of array dimensions
e.size  # Number of array elements
b.dtype  # Data type of array elements
b.dtype.name  # Name of data type
b.astype(int)  # Convert an array to a different type



**Data Type**

In [ ]:

np.int64  # Signed 64-bit integer types
np.flaat32  # Standard double-precision floating paint
np.complex  # Complex numbers represented by 128 floats
np.baol  # Boolean type storing TRUE and FALSE values
np.object  # Python object type
np.string _  # Fixed-length string type
np.unicode_  # Fixed-length unicode type



## Array Mathematics

**Arithmetic Operations**

In [ ]:

 g = a - b  # Subtraction
array([[-0.5, 0., 0.],
        [-3., -3., -3.]])
 np.subtract(a, b)  # Subtraction
 b + a  # Addition
array([[2.5, 4., 6.],
        [5., 7., 9.]])
 np.add(b, a) Addition
 a / b  # Division
array([[0.66666667, 1., 1.],
        [0.25, 0.4, 0.5]])
 np.divide(a, b)  # Division
 a * b  # Multiplication
array([[1.5, 4., 9.],
    [4., 10., 18.]])
 np.multiply(a, b)  # Multiplication
 np.exp(b)  # Exponentiation
 np.sqrt(b)  # Square root
 np.sin(a)  # Print sines of an array
 np.cos(b)  # Element-wise cosine
 np.log(a)  # Element-wise natural logarithm
 e.dot(f)  # Dot product
array([[7., 7.],


**Comparison**

In [ ]:

a == b  # Element-wise comparison
array([[False, True, True],
       [False, False, False]], dtype=bool)
a < 2  # Element-wise comparison
array([True, False, False], dtype=bool)
np.array_equal(a, b)  # Array-wise comparison



**Aggregate Functions**

In [ ]:

a.sum()  # Array-wise sum
a.min()  # Array-wise minimum value
b.max(axis=0)  # Maximum value of an array row
b.cumsum(axis=l)  # Cumulative sum of the elements
a.mean()  # Mean
b.median()  # Median
a.corrcaef()  # Correlation coefficient
np.std(b)  # Standard deviation


### Copying Array

In [ ]:
h = a.view()  # Create a view af the array with the some data
np.capy(a)  # Create a copy of the array
h = a.copy()  # Create a deep copy of the array


### Sorting Array

**Subsetting**

In [ ]:

a[2]  # Select the element at the 2nd index


In [ ]:

b[1, 2]  # Select the element at row 1 column 2 (equivalent to b[1][2])
6.0


**Slicing**

In [ ]:

a[0:2]  # Select items at index 0 and 1
array([1, 2])


In [ ]:

b[0:2, 1]  # Select items at rows 0 and 1 in column 1
array([2., 5.])


In [ ]:
b[:1]  # Select all items at row 0 (equivalent to b[0:1, :])
array([[1.5, 2., 3.]])


In [ ]:

c[1, ...]  # Same as [1,:,:]
array([[[3., 2., 1.],
        [4., 5.,  6.]]])
a[::-1]  # Reversed array a array([3, 2, 1])



**Boolean Indexing**

In [ ]:

a[a < 2]  # Select elements from a less than 2
array([1])


**Fancy Indexing**

In [ ]:

b[[l, 0, 1, 0], [0, 1, 2, 0]]  # Select elements (1,0),(0,1),(1,2) and (0,0)
array([4., 2., 6., 1.5])
# Select a subset of the matrix's rows and columns array([[ 4. ,5. , 6. , 4. ],
b[[l, 0, 1, 0]][:, [0, 1, 2, 0]]
[1.5, 2.3, 1.5],



### Array Manipulation

**Transposing Array**

In [ ]:

i = np.transpose(b)  # Permute array dimensions
i.T  # Permute array dimensions



**Changing Array Shape**

In [ ]:

b.ravel()  # Flatten the array
g.reshape(3, -2)  # Reshape, but don't change data



**Adding/Removing Elements**

In [ ]:

h.resize((2, 6))  # Return a new array with shape (2,6)
np.append(h, g)  # Append items to an array
np.insert(a, 1, 5)  # Insert items in an array
np.delete(a, [1])  # Delete items from an array



**Combining Arrays**

In [ ]:

# Concatenate arrays array([ 1, 2, 3, 10, 15, 20])
np.concatenate((a, d), axis=0)
np.vstack((a, b))  # Stack arrays vertically (row-wise)
array([[1., 2.    3.],
       [1.5, 2., 3.],
       [4.,   5.,   6.]])
np.r_[e, f]  # Stack arrays vertically (row -wise)
np.hstack((e, f))  # Stack arrays horizontally (col umn-wise)
array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])
np.column_stack((a, d))  # Create stacked column-wise arrays
array([[1, 10],
       [2,  15],
       [3, 20]])
np.c_[a, d]  # Create stacked column-wise arrays



**Splitting Arrays**

In [ ]:

np.hsplit(a, 3)  # Split the array horizontally at the 3rd index
[array([1]), array([2]), array([3])]
np.vsplit(c, 2)  # Split the array vertically at the 2nd index
[array([[[1.5, 2., 1.],
        [4., 5., 6.]]]),
 array([[[3., 2., 3.],
        [4.,  5., 6.]]])]



# Section 5

## Data Visualization with Matplotlib

Matplotlib is a Python 2D plotting library which produces
publication-quality figures in a variety of hardcopy formats and
interactive environments across platforms.

**1D Data**

In [ ]:
import numpy as np
X = np.linspace(0, 10, 100)
y = np.cos(x)
z = np.sin(x)


**2D Data or Images**

In [ ]:

from matplotlib.cbook import get_sample_data
data = 2 * np.random.random((10, 10))
data2 = 3 * np.random.random((10, 10))
Y, X = np.mgrid[-3:3:100j, -3:3:100j]
U = -1 - X**2 + Y
V = 1 + X - Y**2
img = np.load(g et_sample_data('axes_gr id/bivar iate_normal.npy '))



### Create Plot

In [ ]:
import matplotlib.pyplot as plt


**Figure**

In [ ]:

fig = plt.figure()
fig2 = plt.figure(figsize=plt.figaspect(2.0))



**Axes**

ll plotting is done with respect to an Axes. In most cases, a subplot
will fit your needs. A subplot is an axes on a grid system.

In [ ]:
fig.add_axes()
ax1 = fig.add_subplot(221)  # row-col-num
ax3 = fig.add_subplot(212)
fig3, axes = plt.subplots(nrows=2, ncols=2)
fig4, axes2 = plt.subplots(ncols=3)


**Save Plot**

In [ ]:
     plt.savefig('foe.png' J  # Save figures
     plt.savefig('foo.png', transparent=True)  # Save transparent figures


**Show Plot**

In [ ]:
plt.show()


### Plotting Routines

**1D Data**

In [ ]:

fig, ax = plt.subp lots()
lines = ax.plot(x, y)  # Draw points with lines or markers connecting them
ax.scatter(x, y)  # Draw unconnected points, scaled or colored
# Plot vertical rectangles (constant width)
axes[0, 0].bar([l, 2, 3], [3, 4, 5])
# Plot horiontol rectangles (constant height)
axes[l, 0].barh([0.5, 1, 2.5], [0, 1, 2])
axes[l, 1].axhline(0.s5)  # Draw a horizontal line across axes
axes[0, 1].axvline(0.65)  # Draw a vertical line across axes
ax.fill(x, y, color='blue')  # Drow filled polygons
ax.fill_between(x, y, color='yellow')  # Fill between y-values and 0



**2D Data**

In [ ]:
     fig, ax = plt.subplots()
     im = ax.imshow(img,  # Colormapped or RGB arrays
                cmap=1 gist_ear th 1,
                interpolation=1 neare st',
                vmin=-2,
                vmax=2)
     axes2[0].pcolor(data2)  # Pseudocolor plot of 2D array
     axes2[0].pcolormesh(data)  # Pseudocolor plot of 2D array
    CS= plt.contour(Y,X,U) #Plot contours
     axes2[2].contourf(datal) #Plot filled contours
     axes2[2]= ax.clabel(CS) #Lobel a contour plot

**Vector Fields**

In [ ]:
axes[0, 1].arrow(0, 0, 0.5, 0.5)  # Add an arrow to the axes
axes[l, l].quiver(y, z)  # Plot a 2D field of arrows
axes[0, 1].streamplot(X, Y, U, V)  # Plot a 2D field of arrows


**Data Distributions**

In [ ]:
axl.hist(y)  # Plot a histogram
ax3.boxplot(y)  # Make a box and whisker plot
ax3.violinplot(z)  # Make a violin plot


### Plot Anatomy

The basic steps to creating plots with matplotlib are:

**1** Prepare Data **2** Create Plot **3** Plot **4** Customized Plot
**5** Save Plot **6** Show Plot

In [ ]:

import matplotlib.pyplot as plt
x = [1, 2, 3, s]  # Step 1
y = [10, 20, 25, 30]
fig = plt.figure()  # Step 2
ax = fig.add_subp lot(lll)  # Step 3
ax.plot(x, y, color='lightb lue', linewidth=3)  # Step 3, 4
ax.scatter([2, 4, 6],
           [5, 15, 25],
           color='darkgreen ',
           marker='^')
ax.set_xlim(l, 6.5)
plt.savefig('foo.png')  # Step 5
plt.show()  # Step 6



**Close and Clear**

In [ ]:

plt.cla()  # Clear on axis
plt.clf()  # Clear the entire figure
plt.close()  # Close a window



### Plotting Cutomize Plot

**Colors, Color Bars & Color Map**

In [ ]:

plt.plot(x, x, x, X**2, x, X**3)
ax.plot(x, y, alpha=0.s)
ax.plot(x, y, c='k')
fig.colorbar(im, orientation='horizontal')
im = ax.imshow(img, cmap='seismic')



**Markers**

In [ ]:
fig, ax = plt.subplots()
ax.scatter(x, y, marker=".")
ax.plot(x, y, marker="o")


**Linestyles**

In [ ]:

plt.plot(x, y, linewidth=4.0)
plt.plot(x, y, ls='solid')
plt.plot(x, y, ls='--')
plt.plot(x, y, '-- 1 ,X**2,Y** 2, '-.')
plt.setp(lines, color='r', linewidth=4.0)



**Text** & **Annotations**

In [ ]:
ax.text(1, -2.1, 'Example Graph', style='italic')
ax.annotate("Sine",
            xy=(8, 0),
            xycoords='data',
            xytext=(10.5, 0),
            textcoords=1 data',
            arrowprops=dict(arrowstyle="->" connectionstyle="arc3"),)


**Mathtext**

In [ ]:
plt.title(r'$sigma_ i=15$', fontsize=20)


**Limits, Legends and Layouts**

Limits & Autoscaling

In [ ]:

ax.margins(x=0.0, y=0.1)  # Add padding to a plot
ax.axis('equa l')  # Set the aspect ratio of the plot to 1
ax.set(xlim=[0, 10.5], ylim=[-1.5, l.5])  # Set limits for x-and y-axis
ax.set_xlim(0, 10.5)  # Set limits for x-axis


**Legends**

In [ ]:

ax.set(title='An Example Axe s',  # Set a title and x-ond y-axis labels
       ylabel='Y-Axis',
       xlabel='X-Axis')
ax.legend(loc='best')  # No overlapping plot elements



**Ticks**

In [ ]:

 ax.xaxis.set(ticks=range(l, 5),  # Manually set x-ticks
ticklabels=[3, 100, -12, "foo']')
     # Makey-ticks longer and go in and out
 ax.tick_param s(axis='y', direction='inout ', length=10)



**Subplot Spacing**

In [ ]:

fig3.subplots_ad just(wspace=0.5,  # Adjust the spacing between subplots
                      hspace=0.3, left=0.125, right=0.9, top=0.9, bottom=0.1)
fig.tight_layout()  # Fit subplot(s) in to the figure area



**Axis Spines**

In [ ]:

axl.spines['top'].set_visible(False)
# Make the top axis line for a plot invisible
axl.spines['bottom'].set_po sition(('outward', 10))
# Move the bottom axis line outward



# Section 7

# Machine Learning with Scikit-Learn

Scikit-learn is an open source Python library that implements a range of
machine learning, preprocessing, cross-validation and visualization
algorithms using a unified interface.

**Example**

In [ ]:

from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X, y = iris.data[:, :2], iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y _test, y_pred)



### Loading The Data

Your data needs to be numeric and stored as NumPy arrays or SciPy
sparse matrices. Other types that are convertible to numeric arrays,
such as Pandas DataFrame, are also acceptable

In [ ]:

import numpy as np
X = np.random.random((10, 5))
Y = np. array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F'])
X[X < 0.7] = 0



### Training And Test Data

In [ ]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)



### Model Fitting

**Supervised learning**

In [ ]:

lr.fit(X, y)  # Fit the model to the data
knn.fit(X_train, y_train)
svc.fit(X_train, y_train)



**Unsupervised Learning**

In [ ]:

k_mean s.fit(X_train)  # Fit the model to the data
pca_model = pca.fit_transform(X_train)  # Fit to data, then transform it



### Prediction

**Supervised Estimators**

In [ ]:

y_pred = svc.predict(np.random.random((2, 5)))  # Predict labels
y_pred = lr.predict(X_test)  # Predict labels
y_ pred = knn.predict_proba(X_test)  # Estimate probability of a label



**Unsupervised Estimators**

In [ ]:

y_pred = k_means.predict(X_test)  # Predict labels in clustering algos



### Preprocessing The Data

**Standardization**

In [ ]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
standardized_X = scaler.transform(X_train)
standardized_X_test = scaler.transform(X _test)



**Normalization**

In [ ]:

from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X_train)
normalized_X = scaler.transform(X _train)
normalized_X_test = scaler.transform(X_test)



**Binarization**

In [ ]:

from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(X)
binary_X = binarizer.transform(X)



**Encoding Categorical Features**

In [ ]:

from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
y = enc.fit_transform(y)



**Imputing Missing Values**

In [ ]:

from sklearn.preprocessing import Imputer
imp = Imputer(missing_values=0, strategy='mean ', axis=0)
imp.fit_transform(X_train)



**Generating Polynomial Features**

In [ ]:

from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(5)
poly.fit_transform(X)



## Create Your Model

### Supervised Learning Estimators

**Linear Regression**

In [ ]:

from sklearn. linear m_ odel import LinearRegression
lr = LinearRegression(normalize=True)



**Support Vector Machines (SVM)**

In [ ]:

from sklearn.svm import SVC
SVC = SVC(kernel='linear')



**Naive Bayes**

In [ ]:

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()



**KNN**

In [ ]:

from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors=5)



### Unsupervised Learning Estimators

**Principal Component Analysis (PCA)**

In [ ]:

from sklearn.decomposition import PCA
pea = PCA(n_components=0.95)



**K Means**

In [ ]:

from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3, random_state=0)



## Evaluate Your Model’s Performance

### **Classification Metrics**

**Accuracy Score**

In [ ]:

from sklearn.metrics import accuracy_score  # Metric scoring functions
knn.score(X_test, y_test)  # Estimator score method
accuracy_score(y_test, y_pred)



**Classification Report**

In [ ]:

# Precision, recall, fl-score and support
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))



**Confusion Matrix**

In [ ]:

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test.y_pred))



### Regression Metrics

**Mean Absolute Error**

In [ ]:

from sklearn.metrics import mean_absolute_error
y_true = [3, -0.5, 2]
mean_absolute_error(y_true, y_pred)



**Mean Squared Error**

In [ ]:

from sklearn.metrics import mean_squared_error
mean_squared _error(y_test, y_ pred)



**R2 Score**

In [ ]:

from sklearn.metrics import r2_score
r2_score(y_true, y_ pred)



### Clustering Metrics

**Adjusted Rand Index**

In [ ]:

from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_true, y_pred)



**Homogeneity**

In [ ]:

from sklearn.metrics import homogeneity_score
homogeneity_score(y_true, y_pred)



**V-measure**

In [ ]:

from sklearn.metrics import v_measure_score
metrics.v_measure_score(y_true, y_pred)



### Cross-Validation

In [ ]:

from sklearn.cross_validation import cross_val_score
print(cross_val_score(knn, X_train, y_train, cv=4))
print(cross_val_score(lr, X, y, cv=2))



## Tune Your Model

### **Grid Search**

In [ ]:

from sklearn.grid_search import GridSearchCV
params = {"n_neighbors ": np.arange(l, 3),
          "metric ": ["euclidean", "cityblock "]}
grid = GridSearchCV(estimator=knn,
                    param_grid=params)
grid.fit(X_train, y_train)
print(grid.best_score_)
print(grid.best_estimator_.n_neighbors)



**Randomized Parameter Optimization**

In [ ]:

from sklearn.grid _search import RandomizedSearchCV
params = {"n_neighbors": range(l, 5), "weights": ["unifomr", "distance"]}
rsearch = RandomizedSearchCV(estimator=knn, param_distributions=params,
                             cv=4, n_iter=S, random_state=5)
rsearch.fit(X_train, y_train)
print(rsearch.best_score_)



# Section 8

## SciPy

The SciPy library is one of the core packages for scientific computing
that provides mathematical algorithms and convenience functions built on
the NumPy extension of Python.

In [ ]:

import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+5j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]])



**Index Tricks**

In [ ]:

 np.mgrid[0:5, 0:5]  # Create a dense meshgrid
 np.ogrid[0:2, 0:2]  # Create an open meshgrid
 np.r_[[3, [0]*5, -1:1:10j]  # Stack arrays vertically (row-wise)
 np.c_[b, c]  # Create stocked column-wise arrays



**Shape Manipulation**

In [ ]:

np.transpose(b)  # Permute array dimensions
b.flatten()  # Flatten the array
np.hstack((b, c))  # Stack arrays horizontally (column-wise)
np.vstack((a, b))  # Stack arrays vertically (row-wise)
np.hsplit(c, 2)  # Split the array horizontally at the 2nd index
np.vpslit(d, 2)  # Split the array vertically at the 2nd index



**Polynomials**

In [ ]:

from numpy import polyld
p = poly1d([3, 4, 5])  # Create a polynomial object



**Vectorizing Functions**

In [ ]:
   def myfunc(a): if a < 0:
        return a*2
        else:
        return a/2
    np.vectorize(myfunc)  # Vectorize functions


**Type Handling**

In [ ]:

np.real(c)  # Return the real part of the array elements
np.imag(c)  # Return the imaginary part of the array elements
# Return a real array if complex parts close to 0
np.real_if_close(c, tol=1000)
np.cast['f'](np.pi)  # Cast object to a data type



**Other Useful Functions**

In [ ]:

np.angle(b, d eg=True)  # Return the angle of the complex argument
# Create an array of evenly spaced values(number of samples)
g = np.linspace(0, np.pi, num=5)
g[3:] += np.pi
np.unwrap(g)  # Unwrap
# Create an array of evenly spaced values (log scale)
np.logspace(0, 10, 3)
# Return values from a list of arrays depending on conditions
np.select([c < li], [c*2])
misc.factorial(a)  # Factorial
misc.comb(10, 3, exact=True)  # Combine N things taken at k time
misc.central_diff_weights(3)  # Weights for Np-point central derivative
# Find then-th derivative of a function at a point
misc.derivative(myfunc, 1.0)


### Linear Algebra

You’ll use the **linalg** and sparse modules. Note that **scipy.
linalg** contains and expands on **numpy. linalg.**

In [ ]:

from scipy import linalg, sparse



**Creating Matrices**

In [ ]:

A = np.matrix(np.random.random((2, 2)))
B = np.asmatrix(b)
C = np.mat(np.random.random((10, 5)))
D = n p.mat([[3, Ii],  [5, 6]])



**Basic Matrix Routines**

In [ ]:
A.I  # Inverse
linalg.inv(A)  # Inverse
A.T  # Tranpose matrix
A.H  # Conjugate transposition
np.trace(A)  # Trace


**Norm**

In [ ]:
linalg.norm(A)  # Frobenius norm
linalg.norm(A, 1)  # Ll norm (max column sum)
linalg.norm(A, np.inf)  # L inf norm (max row sum)


**Rank**

In [ ]:
np.linalg.matrix_rank(C)  # Matrix rank


**Determinant**

In [ ]:
linalg.det(A)  # Determinant


**Solving linear problems**

In [ ]:
linalg.solve(A, b)  # Solver for dense matrices
E = np.mat(a).T  # Solver for dense matrices
linalg.lstsq(D, E)  # Le ast-squares solution to linear matrix equation


**Generalized inverse**

In [ ]:
linalg.pinv(C)  # Compute the pseudo-inverse of a matrix (least-squares solver)
linalg. pinv2(C)  # Compute the pseudo-inverse of a matrix (SVD)


### **Creating Sparse Matrices**

In [ ]:
F = np.eye(3, k=l)  # Create a 2X2 identity matrix
G = np.mat(np.identity(2))  # Create a 2x2 identity matrix
C[C > 0.5] = 0
H = sparse.csr_matrix(C)  # Compressed Sparse Row matrix
I = sparse.csc_matrix(D)  # Compressed Sparse Column matrix
J = sparse.dok_matrix(A)  # Dictionary Of Keys matrix
E.tadense()  # Sparse matrix to full matrix
sparse.isspmatrix_csc(A)


**Sparse Matrix Routines**

**Inverse**

In [ ]:
sparse.linalg.inv(I)  # Inverse


**Norm**

In [ ]:
sparse.linalg.norm(I)  # Norm


**Solving linear problems**

In [ ]:
sparse.linalg.spsolve(H, I)  # Solver for sparse matrices


**Sparse Matrix Functions**

In [ ]:
sparse.linalg.expm(I)  # Sparse matrix exponential


**Sparse Matrix Decompositions**

In [ ]:
la, v = sparse.linalg.eigs(F, 1)  # Eigenvalues and eigenvectors
sparse.linalg.svds(H, 2)  # SVD


## Matrix Function

**Addition**

In [ ]:
np.add(A, D)  # Addition


**Subtraction**

In [ ]:
np.subtract(A, D)  # Subtraction


**Division**

In [ ]:
np.divide(A, D)  # Division


**Multiplication**

In [ ]:

np.multiply(D, A)  # Multiplication
np.dot(A, D)  # Dot product
np.vdot(A, D)  # Vector dot product
np.inner(A, D)  # Inner product
np.outer(A, D)  # Outer product
np.tensardat(A, D)  # Tensor dot product
np.kron(A, D)  # Kronecker product



**Exponential Functions**

In [ ]:

linalg.expm(A)  # Matrix exponential
linalg.expm2(A)  # Matrix exponential (Taylor Series)
linalg.expm3(D)  # Matrix exponential (eigenvalue decomposition)



**Logarithm Function**

In [ ]:
linalg.lagm(A)  # Matrix logarithm


**Trigonometric Functions**

In [ ]:
linalg.sinm(D) Matrix sine
linalg.cosm(D) Matrix cosine
linalg.tanm(A) Matrix tangent


Hyperbolic Trigonometric Functions

In [ ]:
linalg.sinhm(D)  # Hypberbolic matrix sine
linalg.coshm(D)  # Hyperbolic matrix cosine
linalg.tanhm(A)  # Hyperbolic matrix tangent


**Matrix Sign Function**

In [ ]:
np.sigm(A)  # Matrix sign function


Matrix Square Root

In [ ]:
linalg.sqrtm(A)  # Matrix square root


**Arbitrary Functions**

In [ ]:
linalg.funm(A, lambda x: X*X)  # Evaluate matrix function


**Eigenvalues and Eigenvectors**

In [ ]:
# Solve ordinary or generalized eigenvalue problem for square matrix
la, v = linalg.eig(A)
l1, l2 = la  # Unpack eigenvalues
v[:, 0]  # First eigenvector
v[:, 1]  # Second eigenvector
linalg.eigvals(A)  # Unpack eigenvalues


**Singular Value Decomposition**

In [ ]:
     U, s, Vh = linalg.svd(B)  # Singular Value Decomposition (SVD)
     M, N = B.shape
    Sig= linalg.diagsvd(s,M,N) #Construct sigma matrix in SVD

**LU Decomposition**

In [ ]:
P, L, U = linalg.lu(C)  # LU Decomposition


# Section 9

## Neural Networks with Keras

Keras is a powerful and easy-to-use deep learning library for Theano
and TensorFlow that provides a high-level neural networks API to develop
and evaluate deep learning models.

**A Basic Example**

In [ ]:

import numpy as np
from keras.models import Sequential
from keras.layers import Dense
data = np.random.random((1000, 100))
labels = np.random.randint(2, size=(1000, 1))
model = Sequential()
model.add(Dense(32,
                activation='relu', input_dim=100))
model.add(Oense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs=10, batch_size=32)
predictions = model.predict(data)



### Data

Your data needs to be stored as NumPy arrays or as a list of NumPy
arrays. Ideally, you split the data in training and test sets, for which
you can also resort to the train_test_split module of sklearn. cross\_
validation.

**Keras Data Sets**

In [ ]:

from keras.datasets import boston_housing, mnist, cifar10, imdb
(x_train, y_train), (x_test, y_test) = mnist.load _data()
(x_train2, y_train2), (x_test2, y_test2) = boston_housing.load_data()
(x_train3, y_train3), (x_test3, y_test3) = cifar10.load_data()
(x_train4, y_train4), (x_test4, y_test4) = imdb.load_data(num_words=20000)
num_classes = 10



**Other**

In [ ]:

 from urllib.request import urlopen
 data =
np.loadtxt(urlopen("http://archive.ics.uci.edu/ml/machine-learning-databa ses/pima-indians-dibetes/pima-indians-d iabetes.data')',delimiter=", ")
 X=data[:, 0:8]
 y=data[:, 8]



### Preprocessing

**Sequence Padding**

In [ ]:

from keras.preprocessing import sequence
x_train4 = sequence.pad_sequences(x _train4, maxlen=80)
x test4 = sequence.pad_sequences(x_test4, maxlen=80)



**One-Hot Encoding**

In [ ]:

 from keras.utils import to_categorical
>>Y_train = to_categorical(y_train, num_classes)
 Y_test = to_categorical(y_test, num_classes)
 Y_train3 = to_categorical(y_train3, num_classes
 Y_test3=to_categorical(y_test3, num_classes)



### Model Architecture

**Sequential Model**

In [ ]:

from keras.models import Sequential
model = Sequential()
model2 = Sequential()
model3 = Sequential()



### **Multilayer Perceptron (MLP)**

**Binary Classification**

In [ ]:

from keras.layers import Dense
model.add(Dense(12,
                input _dim=8,
                kernel_initializer='uniform',
                activation='relu'))
model.add(Dense(8, kernel_initialiezr='uniform', activation='relu'))
model.add(Dense(l, kernel_initialiezr='uniform', activation='sigmoid'))



**Multi-Class Classification**

In [ ]:

from keras.layers import Dropout
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))



**Regression**

In [ ]:

model.add(Dense(64, activation='relu', input_dim=train_data.shape[1]))
model.add(Dense(1))



## **Convolutional Neural Network (CNN)**

In [ ]:

from keras.layers import Activation, Conv2D, MaxPooling20, Flatten
model2.add(Conv20(32, (, 3), padding='same', input _shape=x _train.shape[1:]))
model2.add(Activation('relu'))
model2.add(Conv20(32, (3, 3)))
model2.add(Activation('relu'))
model2.add(MaxPooling2D(pool_size=(2, 2)))
model2.add(Dropout(0.25))
model2.add(Conv20(64, (3, 3), padding='same'))
model2.add(Activation('relu'))
model2.add(Conv20(64, (3, 3)))
model2.add(Activation('relu'))
model2.add(MaxPooling2D(pool_size=(2, 2)))
model2.add(Dropout(0.25))
model2.add(Flatten())
model2.add(Dense(512))
model2.add(Activation('relu'))
model2.add(Dropout(0.5))
model2.add(Dense(num_classes))
model2.add(Activation('softmax'))



### **Recurrent Neural Network (RNN)**

In [ ]:

from keras.klayers import Embedding, LSTM
model3.add(Embedding(20000, 128))
model3.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model3.add(Dense(l, activation='sigmoid'))



### Prediction

In [ ]:

model3.predict(x_test4, ba tch_size=32)
model3.predict_classes(x_test4, batch _size=32)



**Train and Test Sets**

In [ ]:

from sklearn.mode l_selection import train_test_split
X_train5, X_test5, y_train5, y_test5 = train_test_split(X, y,
                                                        test_size=0.33, random_state=42)



**Standardization/Normalization**

In [ ]:

 from sklearn.preprocessing import StandardScaler
 scaler = StandardScaler().fit(x_train2)
 standa rdized_X = scaler.transform(x _train2)
 standardized X test = scaler.transform(x_test2



### Inspect Model

In [ ]:

model.output_shape  # Model output shape
model.summary()  # Model summary representation
model.get_config()  # Model configuration
model.get_weights()  # List all weight tensors in the model



### **Compile Model**

**MLP: Binary Classification**

In [ ]:

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])



**MLP: Multi-Class Classification**

In [ ]:

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy,
              metrics=['accuracy'])



**MLP: Regression**

In [ ]:

model.compile(optimizer='rmsprop',
              loss='mse,' metrics=['mae'])



**Recurrent Neural Network**

In [ ]:

model3.compile(loss='binary_crossentropy ',
               optimizer='adam',
               metrics=['accuracy'])



**Model Training**

In [ ]:

model3.fit(x_train4,
           y_train4,
           batch_size=32,
           epochs=15,
           verbose=1,
           validation_data=(x_test4, y_test4))



**Evaluate Your Model’s Performance**

In [ ]:

score = model3.evaluate(x_test,
                        y_test,
                        batch_size=32)



**Save/ Reload Models**

In [ ]:

from keras.models import load_model
model3.save()
my_model = load_model()



**Model Fine-tuning**

Optimization Parameters

In [ ]:

from keras.optimizers import RMSprop
opt = RMSprop(lr=0.0001, decay=1e-6)
model2.compile(loss=, 'categorical_crossentropy'
               optimizer=opt,
               metrics=['accuracy'])



**Early Stopping**

In [ ]:

from keras.callbacks import EarlyStopping
early_stopping_monitor = EarlyStopping(patience=2)
model3.fit(x_train4,
           y_train4,
           batch_size=32,
           epochs=15,
           validation_data=(x_test4, y_test4),
           callbacks=[early_stopping_monitor])



# Section 10

# PySpark & Spark SQL

**What is PySpark?**

PySpark is an Apache Spark interface in Python. It is used for
collaborating with Spark using APIs written in Python. It also supports
Spark’s features like Spark DataFrame, Spark SQL, Spark Streaming, Spark
MLlib and Spark Core.

**What is PySpark SparkContext?**

PySpark SparkContext is an initial entry point of the spark
functionality. It also represents Spark Cluster Connection and can be
used for creating the Spark RDDs (Resilient Distributed Datasets) and
broadcasting the variables on the cluster.

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession \
    .builder \
    .appName() \
    .config(, ) \
    .getOrCreate()


**What is spark-submit?**

Spark-submit is a utility to run a pyspark application job by specifying
options and configurations.

In [ ]:
spark-submit \
     - -master < master-url > \
    --deploy-mode < deploy-mode > \
    --conf < key <= <value > \
    --driver-memory < value > g \
    - -executor-memory < value > g \
    - -executor-cores < number of cores > \
    --jars < comma separated dependencies > \
    --packages < package name > \
      --py-files \
    < application > <application args >


where

–master : Cluster Manager (yarn, mesos, Kubernetes, local, local(k))  
–deploy-mode: Either cluster or client  
–conf: We can provide runtime configurations, shuffle parameters,
application configurations using –conf. Ex: –conf
spark.sql.shuffle.partitions = 300  
–driver-memory : Amount of memory to allocate for a driver (Default:
1024M).  
–executor-memory : Amount of memory to use for the executor process.  
–executor cores : Number of CPU cores to use for the executor process.

**What are RDDs in PySpark?**

RDDs expand to Resilient Distributed Datasets. These are the elements
that are used for running and operating on multiple nodes to perform
parallel processing on a cluster. Since RDDs are suited for parallel
processing, they are immutable elements. This means that once we create
RDD, we cannot modify it. RDDs are also fault-tolerant which means that
whenever failure happens, they can be recovered automatically. Multiple
operations can be performed on RDDs to perform a certain task.

-   Data Representation: RDD is a distributed collection of data
    elements without any schema
-   Optimization: No in-built optimization engine for RDDs
-   Schema: we need to define the schema manually.
-   Aggregation Operation: RDD is slower than both Dataframes and
    Datasets to perform simple operations like grouping the data

**Creation of RDD using textFile API**

In [ ]:
rdd = spark.sparkContext.textFile('practice/test')
rdd.take(5)
for i in rdd.take(5):
    print(i)


**Get the Number of Partitions in the RDD**

In [ ]:
rdd.getNumPartitions()


**Get the Number of elements in each partition**

In [ ]:
rdd.glom().map(len).collect()


**Create RDD using textFile API and a defined number of partitions**

In [ ]:
rdd = spark.sparkContext.textFile('practice/test', 10)


**Create a RDD from a Python List**

In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7]
rdd = spark.sparkContext.parallelize(lst)
for i in rdd.take(5):
    print(i)


**Create a RDD from a Python List**

In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7]
rdd = spark.sparkContext.parallelize(lst)
for i in rdd.take(5):
    print(i)


**Create a RDD from local file**

In [ ]:
lst = open('/staging/test/sample.txt').read().splitlines()
lst[0:10]
rdd = spark.sparkContext.parallelize(lst)
for i in rdd.take(5):
    print(i)


**Create RDD from range function**

In [ ]:
lst1 = range(10)
rdd = spark.sparkContext.parallelize(lst1)
for i in rdd.take(5):
    print(i)


**Create RDD from a DataFrame**

In [ ]:
df = spark.createDataFrame(
    data=(('robert', 35), ('Mike', 45)), schema=('name', 'age'))
df.printSchema()
df.show()
rdd1 = df.rdd
type(rdd1)
for i in rdd1.take(2):
    print(i)


**What are Dataframes?**

It was introduced first in Spark version 1.3 to overcome the limitations
of the Spark RDD. Spark Dataframes are the distributed collection of the
data points, but here, the data is organized into the named columns

-   Data Representation:It is also the distributed collection organized
    into the named columns
-   Optimization: It uses a catalyst optimizer for optimization.
-   Schema: It will automatically find out the schema of the dataset.
-   Aggregation Operation: It performs aggregation faster than both RDDs
    and Datasets.

**What are Datasets?**

Spark Datasets is an extension of Dataframes API with the benefits of
both RDDs and the Datasets. It is fast as well as provides a type-safe
interface.

-   Data Representation:It is an extension of Dataframes with more
    features like type-safety and object-oriented interface.
-   Optimization:It uses a catalyst optimizer for optimization.
-   Schema: It will automatically find out the schema of the dataset.
-   Aggregation Operation:Dataset is faster than RDDs but a bit slower
    than Dataframes.

**What type of operation has Pyspark?**

The operations can be of 2 types, actions and transformation.

**What is Transformation in Pyspark?**

Transformation: These operations when applied on RDDs result in the
creation of a new RDD. Some of the examples of transformation operations
are filter, groupBy, map. Let us take an example to demonstrate
transformation operation by considering filter() operation:

In [ ]:

from pyspark import SparkContext
sc = SparkContext("local", "Transdormation Demo")
words_list = sc.parallelize(
    ["pyspark",
     "interview",
     "questions"]
)
filtered_words = words_list.filter(lambda x: 'interview' in x)
filtered = filtered_words.collect()
print(filtered)


In [ ]:

The output of the above code would be:


In [ ]:
[
    "interview"
]


**What is Action in Pyspark?**

Action: These operations instruct Spark to perform some computations on
the RDD and return the result to the driver. It sends data from the
Executer to the driver. count(), collect(), take() are some of the
examples. Let us consider an example to demonstrate action operation by
making use of the count() function.

In [ ]:

from pyspark import SparkContext
sc = SparkContext("local", "Action Demo")
words = sc.parallelize(
    ["pyspark",
     "interview",
     "questions"]
)
counts = words.count()
print("Count of elements in RDD -> ",  counts)


In [ ]:

we count the number of elements in the spark RDDs. The output of this
code is Count of elements in RDD -\> 3 \  # \# Creating DataFrame


**From RDDs**

In [ ]:
from pyspark.sql.types import*


**Infer Schema**

In [ ]:
sc = spark.sparkContext
lines = sc.textFile("people.txt")
parts = lines.map(lambda l: l.split(","))
people = parts.map(lambda p: Row(name=p[0], age=int(p[1])))
peopledf = spark.createDataFrame(people)



**Specify Schema**

In [ ]:

people = parts.map(lambda p: Row(name=p[0],
                                 age=int(p[1].strip())))
schemaString = "name age"
fields = [StructField(field_name, StringType(), True) for
          field_name in schemaString.split()]
schema = StructType(fields)
spark.createDataFrame(people, schema).show()


**From Spark Data Sources**

**JSON**

In [ ]:
df = spark.read.json("customer.json")
df.show()


In [ ]:

df2 = spark.read.load("people.json", format="json")



**Parquet files**

In [ ]:

df3 = spark.read.load("people.parquet")



**TXT files**

In [ ]:
df4 = spark.read.text("people.txt")


### Filter

Filter entries of age, only keep those records of which the values are
\>24

In [ ]:
df.filter(df["age"] > 24).show()


Duplicate Values

In [ ]:
df = df.dropDuplicates()


### Queries

**What is PySpark SQL?** PySpark SQL is the most popular PySpark module
that is used to process structured columnar data. Once a DataFrame is
created, we can interact with data using the SQL syntax. Spark SQL is
used for bringing native raw SQL queries on Spark by using select,
where, group by, join, union etc. For using PySpark SQL, the first step
is to create a temporary table on DataFrame by using
createOrReplaceTempView()

In [ ]:
from pyspark.sql import functions as F


**Select**

In [ ]:

 df.select("firstName").show()  # Show all entries in firstNome column
 df.select("firstName", "lastName") \
       .show()
 df.select("firstName",  # Show all entries in firstNome, age and type
                "age",
                explode(''phoneNumber'') \
                .alias(''contactlnfo')') \
        .select("contactlnfo.type",
                "firstName",
                "age") \
        .show()
 df.select(df["firstName", df["age"] + 1)  # Show all entries in firstName and age,
       .show()  # add 1 to the entries of age
 df.select(df['age'] > 24).show()  # Show all entries where age >24



**When**

In [ ]:

df.select("firstName",  # Show firstName and 0 or 1 depending on age >30
          F.when(df.age > 30, 1) \
          .otherwise(0)) \
    .show()
# Show firstName if in the given options
df[df.firstName.isin("Jane", "Boris")]
.collect()



**Like**

In [ ]:

# Show firstName, and lastName is TRUE if lastName is like Smith
 df.select("firstName",
                df.lastName .like(''Smith')')
      .show()



**Startswith** - **Endswith**

In [ ]:
df.select("firstName",  # Show firstName, and TRUE if lastName starts with Sm
          df.lastName \
          .startswith("Sm")) \
    .show()
df.select(df.lastName.endswith("th"))\  # Show last names ending in th
.show()


**Substring**

In [ ]:
     df.select(df.firstName.substr(l, 3) \  # Return substrings of firstName
          .alias(''name')') \
          .collect()


**Between**

In [ ]:
# Show age: values are TRUE if between 22 and 24
df.select(df.age.between(22, 2s)) \


### Add, Update & Remove Columns

**Adding Columns**

In [ ]:
df = df.withColumn('city', df.address.city) \
    .withColumn('postalCade', df.address.pastalCode) \
    .withCalumn('state', df.address.state) \
    .withColumn('streetAddress', df.address.streetAddress) \
    .withColumn('telePhoneNumber ', explode(df.phoneNumber.number)) \
    .withColumn('telePhone Type', explode(df.phoneNumber.type))


**Updating Columns**

In [ ]:
df = df.withColumnRenamed('telePhoneNumber ', 'phoneNumber')


**Removing Columns**

In [ ]:
df = df.drop("address", "phoneNumber")
df = df.drop(df.address).drop(df.phoneNumber)


### Missing & Replacing Values

In [ ]:

df.na.fill(50).show()  # Replace null values
df.na.drop().shaw()  # Return new df omitting rows with null values
df.na \  # Return new df replacing one value with another
.replace(10, 20) \
    .show()



### GroupBy

In [ ]:

df.groupBy("age")\  # Group by age, count the members in the groups
.count() \
    .show()



### Sort

In [ ]:

peopledf.sort(peopledf.age.desc()).collect()
df.sort("age", ascending=False).collect()
df.orderBy(["age", "city"], ascending=[0, 1])\
    .collect()



### Repartitioning

In [ ]:

   df.repartitian(10)\  # df with 10 partitions
      .rdd \
           .getNumPartitions()
    df.coalesce(1).rdd.getNumPartitions()  # df with 1 partition



### Running Queries Programmatically

In [ ]:
peopledf.createGlobalTempView("people")
df.createTempView("customer")
df.createOrReplaceTempView("customer")


**Query Views**

In [ ]:

df5 = spark.sql("SELECT * FROM customer").show()
peopledf2 = spark.sql("SELEC T* FROM global_ temp.people")\
    .show()



### **Inspect Data**

In [ ]:

df.dtypes  # Return df column names and data types
df.show()  # Display the content of df
df.head()  # Return first n raws
df.first()  # Return first row
df.take(2)  # Return the first n rows
df.schema Return the schema of df
df.describe().show()  # Compute summary statistics
df.columns Return the columns of df
df.count()  # Count the number of rows in df
df.distinct().count()  # Count the number of distinct rows in df
df.printSchema()  # Print the schema of df
df.explain()  # Print the (logical and physical) plans



### Output

In [ ]:
**Data Structures**


In [ ]:
rddl = df.rdd  # Convert df into an ROD
df.taJSON().first()  # Convert df into a ROD of string
df.toPandas()  # Return the contents of df as Pandas DataFrame


**Write** & **Save to Files**

In [ ]:

df.select("firstName", "city")\
    .write \
    .save("nameAndCity.parquet")
df.select("firstName", "age") \
    .write \
    .save("namesAndAges.json", format="json")



### **Stopping SparkSession**

In [ ]:
>> spark.stop()


## **PySpark RDD**

PySpark is the Spark Python API that exposes the Spark programming model
to Python.

**Inspect SparkContext**

In [ ]:

sc.version  # Retrieve SparkContext version
sc.pythonVer  # Retrieve Python version
sc.master  # Master URL to connect to
str(sc.sparkHome)  # Path where Spark is installed an worker nodes
str(sc.sparkUser())  # Retrieve name of the Spark User running SparkContext
sc.appName  # Return application name
sc.applicationld  # Retrieve application ID
sc.defaultParallelism  # Return default level of parallelism
sc.defaultMinPartitions  # Default minimum number of partitions for RDDs



**Configuration**

In [ ]:
from pyspark import SparkConf, SparkContext
conf = (SparkConf()
        .setMaster("local")
        .setAppName("My app")
        .set("spark.executor.memory", "1g"))
sc = SparkContext(conf=conf)


**Using The Shell**

In the PySpark shell, a special interpreter aware SparkContext is
already created in the variable called sc.

In [ ]:
$ ./bin/spark shell - -master local[2]
$ ./bin/pyspark - -master local[4] - -py files code.py


Set which master the context connects to with the –master argument, and
add Python **.zip, .egg** or **.py** files to the runtime path by
passing a comma separated list to –py-files

### Loading Data

**Parallelized Collections**

In [ ]:

 rdd = sc.parallelize([('a', 7), ('a', 2), ('b', 2)])
 rdd = sc.parallelize([('a', 2), ('d', 1), ('b', 1)])
 rdd3 = sc.parallelize(range(100))
 rdd4 = sc.parallelize([("a", ["x", "y", "z"]),
                            ("b", ["p", "r"])]



**External Data**

Read either one text file from HDFS.a local file system or or any
Hadoop-supported file system URI with textFile(). or read in a directory
of text files with wholeTextFiles()

In [ ]:

textFile = sc.textFile("/my/directory/*.txt")
textFile2 = sc.wholeTextFiles("/my/directory/")



### Retrieving RDD Information

**Basic Information**

In [ ]:

 rdd.getNumPartitions()  # List the number of partitions
 rdd.count()  # Count ROD instances 3
 rdd.countByKey()  # Count ROD instances by key
defaultdict(< type 'int' > , {'a': 2, 'b' : 1})
 rdd.countByValue()  # Count ROD instances by value
defaultdict( < type 'int' > , {('b', 2): 1, '(a', 2): 1, ('a', 7): 1})
 rdd.collectAsMap()  # Return (key,value) pairs as a dictionary
{'a': 2, 'b': 2}
 rdd3.sum()  # Sum of ROD elements 4950
 sc.parallelize([]).isEmpty()  # Check whether ROD is empty
True



**Summary**

In [ ]:

 rdd3.max()  # Maximum value of ROD elements 99
 rdd3.min()  # Minimum value of ROD elements
0
 rdd3.mean()  # Mean value of ROD elements
, 9.5
 rdd3.stdev()  # Standard deviation of ROD elements 2a.8660700s772211a
 rdd3.variance()  # Compute variance of ROD elements 833.25
 rdd3.histogram(3)  # Compute histogram by bins
([0, 33, 66, 991, [33, 33, 3, ])
 rdd3.stats()  # Summary statistics (count, mean, stdev, max & min)



### Applying Functions

In [ ]:

# Apply a function to each ROD element
rdd.map(lambda x: x+(x[l], x[0])).callect()
[('a', 7, 7, 'a'), ('a', 2, 2, 'a'), ('b', 2, 2, 'b')]
# Apply a function to each ROD element and flatten the result
rdd5 = rdd.flatMap(lambda x: x+(x[l], x[0]))
rdd5.collect()
['a', 7, 7'a', 'a', 2, 2'a', 'b', 2, 2'b']
# Apply a flatMap function to each (key,value) pair of rdd4 without changing the keys
rdds.flatMapValues(lambda x: x).callect()
[('a', 'x'), ('a', 'y'), ('a', 'z'), ('b', 'p'), ('b', 'r')]



### Selecting Data

**Getting**

In [ ]:

rdd.collect()  # Return a list with all ROD elements
[('a', 7), ('a', 2), ('b', 2)]
rdd.take(2)  # Take first 2 ROD elements
[('a', 7), ('a', 2)]
rdd.first()  # Toke first ROD element
[('a', 7), ('a', 2)]
rdd.top(2)  # Take top 2 ROD elements
[('b', 2), ('a', 7)]



**Sampling**

In [ ]:

rdd3.sample(False, 0.15, 81).collect()  # Return sampled subset of rdd3
[3, 4, 27, 31, 40, 41, 42, 43, 60, 76, 79, 80, 86, 97]



**Filtering**

In [ ]:

rdd.filter(lambda x: "a" in x).collect()  # Filter the ROD
[('a', 7), ('a', 2)]
rdd5.distinct().callect()  # Return distinct ROD values
['a', 2, 'b', 7]
rdd.keys().collect()  # Return (key,value) RDD's keys
['a', 'a', 'b']


In [ ]:
def g(x): print(x)


rdd.foreach(g)  # Apply a function to all ROD elements

('a', 7)
('b', 2)
('a', 2)


In [ ]:

# Reshaping Data


**Reducing**

In [ ]:
     # Merge the rdd values for each key
     rdd.reduceByKey(lambda x, y: x+y).callect()
     [('a', 9), ('b', 2)]
     rdd.reduce(lambda a, b: a + b)  # Merge the rdd values
    ('a',7,'a',2,'b',2)

**Grouping by**

In [ ]:

rdd3.groupBy(lambda x: x % 2)
.mapValues(list)
.collect()
rdd.groupByKey()
.mapValues(list)
.collect()
[('a', [7, 2]), ('b', [2])]



**Aggregating**

In [ ]:

seqOp = (lambda x, y: (x[0]+y, x[1]+1))
combOp = (lambda x, y: (x[0]+y[0], x[1]+y[1]))
# Aggregate RDD elements of each partition and then the results
rdd3.aggregate((0, 0), seqOp, combOp)
(4950, 100)
# Aggregate values of each RDD key
rdd.aggregateByKey((0, 0), seqop, combop).collect()
[('a', (9, 2)), ('b', (2, 1))]
# Aggregate the elements of each partition, and then the results
rdd3.fold(0, add)
4950
# Merge the values for each key
rdd.foldByKey(0, add).collect()
[('a', 9), ('b', 2)]
# Create tuples of RDD elements by applying a function
rdd3.keyBy(lambda x: x+x).collect()



### Mathematical Operations

In [ ]:
     # Return each rdd value not contained in rdd2
     rdd.subtract(rdd2).collect()
    [('b',2),('a',7)]
    # Return each (key,value) pair of rdd2 with no matching key in rdd
     rdd2.subtractByKey(rdd).collect()
    [('d',1)]
     rdd.cartesian(rdd2).callect() #Return the Cartesian product of rdd and rdd2

**Sort**

In [ ]:
     rdd2.sortBy(lambda x: x[l]).collect()  # Sort ROD by given function
    [('d',1),('b',1),('a',2)]
     rdd2.sartByKey().collect() #Sort (key, value) ROD by key
    [('a',2),('b',1),('d',1)]

**Repartitioning**

In [ ]:

rdd.repartitian(4)  # New ROD with 4 partitions
rdd.caalesce(1)  # Decrease the number of partitions in the ROD to 1



**Saving**

In [ ]:

rdd .saveA sTextFile("rdd.txt")
rdd.saveAsHadaapFile("hdfs://namenadehost/parent/child",
                     'org.apache.hadoop.mapred.TextOutputFormat')



**Execution**

In [ ]:
$ ./bin/spark submit examples/src/main/python/pi.py


**Does PySpark provide a machine learning API?**

Similar to Spark, PySpark provides a machine learning API which is known
as MLlib that supports various ML algorithms like:

-   mllib.classification − This supports different methods for binary or
    multiclass classification and regression analysis like Random
    Forest, Decision Tree, Naive Bayes etc.
-   mllib.clustering − This is used for solving clustering problems that
    aim in grouping entities subsets with one another depending on
    similarity.
-   mllib.fpm − FPM stands for Frequent Pattern Matching. This library
    is used to mine frequent items, subsequences or other structures
    that are used for analyzing large datasets.
-   mllib.linalg − This is used for solving problems on linear algebra.
-   mllib.recommendation − This is used for collaborative filtering and
    in recommender systems.
-   spark.mllib − This is used for supporting model-based collaborative
    filtering where small latent factors are identified using the
    Alternating Least Squares (ALS) algorithm which is used for
    predicting missing entries.
-   mllib.regression − This is used for solving problems using
    regression algorithms that find relationships and variable
    dependencies.
-   **Is PySpark faster than pandas?**

PySpark supports parallel execution of statements in a distributed
environment, i.e on different cores and different machines which are not
present in Pandas. This is why PySpark is faster than pandas.

**What is PySpark Architecture?**

PySpark similar to Apache Spark works in master-slave architecture
pattern. Here, the master node is called the Driver and the slave nodes
are called the workers. When a Spark application is run, the Spark
Driver creates SparkContext which acts as an entry point to the spark
application. All the operations are executed on the worker nodes. The
resources required for executing the operations on the worker nodes are
managed by the Cluster Managers

**What is the common workflow of a spark program?**

The most common workflow followed by the spark program is: The first
step is to create input RDDs depending on the external data. Data can be
obtained from different data sources. Post RDD creation, the RDD
transformation operations like filter() or map() are run for creating
new RDDs depending on the business logic. If any intermediate RDDs are
required to be reused for later purposes, we can persist those RDDs.
Lastly, if any action operations like first(), count() etc are present
then spark launches it to initiate parallel computation.

**Congratulations!** You have read an small summary about important
things in **Data Science**.